id: sys.core.flow
display_name: Flow
facets:
  - isFlow
  - isContainer
containment:
  must_live_under: []
  may_contain:
    - facet: isCompute
    - kind: sys.engine.read_slot
    - kind: sys.engine.write_slot
    - kind: sys.core.flow
    - kind: ui.nav
    - kind: ui.page
    - kind: ui.template
    - kind: ui.widget
  cardinality_per_parent: many_per_parent
  cascade: strict
slots: []
